### ISSUE TITLE
Convergence of 3D problems in parallel

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/mfmg#39]
When using mpi, the convergence in 3D is degraded. We need to understand why. It could be due to the way the agglomerate are formed in 3D

**Comment by aprokop** [comment]
You should have the same problem in 2D. If you agglomerates are the same, then typically the convergence suffers because your smoothers are less effective. For instance, using Gauss-Seidel you smoothe within each subdomain independently. There some things that can slightly help, for instance using `l1` Gauss-Seidel, but I'm not sure if deal.ii supports those.

**Comment by Rombur** [comment]
Given the importance of the smoothers for the two-grids and @aprokop's explanation, the convergences difference makes sense.  Below is a table of the convergences of the tests in `test_hierarchy/hierarchy_3d` for 1 and 2 proc.

| Configuration | 1 proc  | 2 proc |
| ----------------- | --------- | -------- |
| hyper_cube; false; Reverse Cuthill_McKee | 0.042511110599999999 | 0.098747812625821621 |
| hyper_cube; true; None | 0.039867204400000002 | 0.085410833018491811 |
| hyper_cube; true; Reverse Cuthill_McKee | 0.039867204400000002 | 0.085410833018491811 |
| hyper_ball; false; None | 0.1303442282 | 0.16791412508975309 |
| hyper_ball; false; Reverse Cuthill_McKee | 0.1303442282 | 0.16791412508975309 |
| hyper_ball; true; None | 0.14310964679999999 | 0.18079990250219188 |
| hyper_ball; true; Reverse Cuthill_McKee | 0.14310964679999999 | 0.18079990250219188 |
